package org.specialtripsagency;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(57f7f0433a8c24e667009b40982fcaed)
 */
public class BookingObject extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    private java.lang.Integer additionalPriceDiscount;
    
    private Applicant applicant;
    private Flight availableFlights;
    private Hotel availableHotels;
    private Boolean bookingConfirmed;
    private Integer bookingId;
    private PaymentDetails paymentDetails;
    
    private String reviewerComment;
    
    private Integer totalPrice;
    
    private TravelDetails travelDetails;

    public BookingObject() {
    }

    public BookingObject(Applicant applicant, org.specialtripsagency.TravelDetails travelDetails, org.specialtripsagency.Flight availableFlights, org.specialtripsagency.Hotel availableHotels, java.lang.Integer totalPrice, java.lang.Integer additionalPriceDiscount, java.lang.Integer bookingId, java.lang.String reviewerComment, java.lang.Boolean bookingConfirmed, org.specialtripsagency.PaymentDetails paymentDetails) {
        this.applicant = applicant;
        this.travelDetails = travelDetails;
        this.availableFlights = availableFlights;
        this.availableHotels = availableHotels;
        this.totalPrice = totalPrice;
        this.additionalPriceDiscount = additionalPriceDiscount;
        this.bookingId = bookingId;
        this.reviewerComment = reviewerComment;
        this.bookingConfirmed = bookingConfirmed;
        this.paymentDetails = paymentDetails;
    }


    
    public java.lang.Integer getAdditionalPriceDiscount() {
        return this.additionalPriceDiscount;
    }

    public void setAdditionalPriceDiscount(java.lang.Integer additionalPriceDiscount) {
        this.additionalPriceDiscount = additionalPriceDiscount;
    }
    
    public Applicant getApplicant() {
        return this.applicant;
    }

    public void setApplicant(Applicant applicant) {
        this.applicant = applicant;
    }
    
    public org.specialtripsagency.Flight getAvailableFlights() {
        return this.availableFlights;
    }

    public void setAvailableFlights(Flight availableFlights) {
        this.availableFlights = availableFlights;
    }
    
    public org.specialtripsagency.Hotel getAvailableHotels() {
        return this.availableHotels;
    }

    public void setAvailableHotels(Hotel availableHotels) {
        this.availableHotels = availableHotels;
    }
    
    public java.lang.Boolean getBookingConfirmed() {
        return this.bookingConfirmed;
    }

    public void setBookingConfirmed(java.lang.Boolean bookingConfirmed) {
        this.bookingConfirmed = bookingConfirmed;
    }
    
    public java.lang.Integer getBookingId() {
        return this.bookingId;
    }

    public void setBookingId(java.lang.Integer bookingId) {
        this.bookingId = bookingId;
    }
    
    public org.specialtripsagency.PaymentDetails getPaymentDetails() {
        return this.paymentDetails;
    }

    public void setPaymentDetails(PaymentDetails paymentDetails) {
        this.paymentDetails = paymentDetails;
    }
    
    public java.lang.String getReviewerComment() {
        return this.reviewerComment;
    }

    public void setReviewerComment(java.lang.String reviewerComment) {
        this.reviewerComment = reviewerComment;
    }
    
    public java.lang.Integer getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(java.lang.Integer totalPrice) {
        this.totalPrice = totalPrice;
    }
    
    public org.specialtripsagency.TravelDetails getTravelDetails() {
        return this.travelDetails;
    }

    public void setTravelDetails(TravelDetails travelDetails) {
        this.travelDetails = travelDetails;
    }
}