package org.specialtripsagency;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(d8f4abe76caf3d8e5439d1b9fdb5e0d4)
 */
public class Hotel extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    private java.lang.Boolean breakfastIncluded;
    
    private java.lang.Integer duration;
    
    private java.lang.Integer hotelId;
    
    private java.lang.String hotelName;
    
    private java.lang.String location;
    
    private java.lang.Integer priceDiscount;
    
    private java.lang.Integer roomPrice;
    
    private java.lang.String roomType;

    public Hotel() {
    }

    public Hotel(java.lang.String hotelName, java.lang.Integer hotelId, java.lang.Integer roomPrice, java.lang.Integer duration, java.lang.String roomType, java.lang.String location, java.lang.Boolean breakfastIncluded, java.lang.Integer priceDiscount) {
        this.hotelName = hotelName;
        this.hotelId = hotelId;
        this.roomPrice = roomPrice;
        this.duration = duration;
        this.roomType = roomType;
        this.location = location;
        this.breakfastIncluded = breakfastIncluded;
        this.priceDiscount = priceDiscount;
    }


    
    public java.lang.Boolean getBreakfastIncluded() {
        return this.breakfastIncluded;
    }

    public void setBreakfastIncluded(java.lang.Boolean breakfastIncluded) {
        this.breakfastIncluded = breakfastIncluded;
    }
    
    public java.lang.Integer getDuration() {
        return this.duration;
    }

    public void setDuration(java.lang.Integer duration) {
        this.duration = duration;
    }
    
    public java.lang.Integer getHotelId() {
        return this.hotelId;
    }

    public void setHotelId(java.lang.Integer hotelId) {
        this.hotelId = hotelId;
    }
    
    public java.lang.String getHotelName() {
        return this.hotelName;
    }

    public void setHotelName(java.lang.String hotelName) {
        this.hotelName = hotelName;
    }
    
    public java.lang.String getLocation() {
        return this.location;
    }

    public void setLocation(java.lang.String location) {
        this.location = location;
    }
    
    public java.lang.Integer getPriceDiscount() {
        return this.priceDiscount;
    }

    public void setPriceDiscount(java.lang.Integer priceDiscount) {
        this.priceDiscount = priceDiscount;
    }
    
    public java.lang.Integer getRoomPrice() {
        return this.roomPrice;
    }

    public void setRoomPrice(java.lang.Integer roomPrice) {
        this.roomPrice = roomPrice;
    }
    
    public java.lang.String getRoomType() {
        return this.roomType;
    }

    public void setRoomType(java.lang.String roomType) {
        this.roomType = roomType;
    }
}