package org.specialtripsagency;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(d5a78195e4b6e25da4f3b49100692e5d)
 */
public class PaymentDetails  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    private java.lang.String creditCardNumber;
    
    private java.lang.String expiryDate;
    
    private java.lang.String nameOfCardHolder;

    public PaymentDetails() {
    }

    public PaymentDetails(java.lang.String creditCardNumber, java.lang.String expiryDate, java.lang.String nameOfCardHolder) {
        this.creditCardNumber = creditCardNumber;
        this.expiryDate = expiryDate;
        this.nameOfCardHolder = nameOfCardHolder;
    }


    
    public java.lang.String getCreditCardNumber() {
        return this.creditCardNumber;
    }

    public void setCreditCardNumber(java.lang.String creditCardNumber) {
        this.creditCardNumber = creditCardNumber;
    }
    
    public java.lang.String getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(java.lang.String expiryDate) {
        this.expiryDate = expiryDate;
    }
    
    public java.lang.String getNameOfCardHolder() {
        return this.nameOfCardHolder;
    }

    public void setNameOfCardHolder(java.lang.String nameOfCardHolder) {
        this.nameOfCardHolder = nameOfCardHolder;
    }
}